documentation updated with icon import and cinnabar/zinc
tangrams/cartography-docs pull request #35
Opened 2017-08-16 16:37 UTC by sensescape

2017-08-16 16:44 UTC, nvkelso commented on icons.md
> +            mapzen_icon_library:
We should have two examples, one that is:

```
         draw:
            mapzen_icon_library:
               sprite: zoo
```

```
Second that says if your data has a kind property with one of the values in the table below, it'll just show up:

```
         draw:
            mapzen_icon_library: {}
```

2017-08-16 16:46 UTC, nvkelso commented on icons.md
> +* Bubble Wrap: `7.0.0 and later`
Keep at the original number (back to 6), same for below...

2017-08-16 16:47 UTC, nvkelso commented on styles.md
> +## Cinnabar and Zinc
This would just be `Cinnabar`.

2017-08-16 16:50 UTC, nvkelso commented on themes.md
> +Zinc is now a color theme of Cinnabar.
To: `Cinnabar is offered in one additional color theme: Zinc.`

2017-08-16 16:54 UTC, nvkelso commented on icons.md
> +            mapzen_icon_library:
Ah, the top example in full:

```
import:
    - https://mapzen.com/carto/refill-style/refill-style.zip

sources:
    my-source:
        type: GeoJSON
        url:  https://example.com/filename.geojson
        max_zoom: 16

layers:
    my-layer:
        data:
            source: my-source
        draw:
            mapzen_icon_library:
                sprite: zoo
            # if your data includes a kind property with values in the table below
            # mapzen_icon_library: {}
```

2017-08-16 16:57 UTC, nvkelso commented on icons.md
> +    - https://mapzen.com/carto/refill-style/refill-icons.zip
I think this whole section goes to:

```
import:
     - https://mapzen.com/carto/refill-style/refill-icons.zip
 
sources:
    my-source:
        type: GeoJSON
        url:  https://example.com/filename.geojson
        max_zoom: 16

layers:
    my-layer:
        data:
            source: my-source
        draw:
            mapzen_icon_library:
                sprite: zoo
            # if your data includes a kind property with values in the table below
            # the sprite will be sourced per feature to the appropriate icon
            # mapzen_icon_library: {}
```

2017-08-16 16:57 UTC, nvkelso commented on icons.md
> +You can use the icons in this library independent of one of the Mapzen basemap styles, but there are a few required steps to doing this in Tangram:
You can remove: `, but there are a few required steps to doing this in Tangram:`

2017-08-16 16:57 UTC, nvkelso commented on icons.md
> +- You'll need to setup your own textures block with the spritesheet, and named sprites block.
This list can be removed.

2017-08-16 17:00 UTC, nvkelso commented on icons.md
> +You can use the icons in this library independent of one of the Mapzen basemap styles, but there are a few required steps to doing this in Tangram:
To:

`You can use the icons in the Mapzen icon library independent of one of the Mapzen basemap styles by importing just the icon assets.`

2017-09-11 21:16 UTC, nvkelso commented
Per IRL discussions we're moving Zinc to be a theme of Refill, which means the Zinc documentation here needs to be updated.

2017-09-11 21:17 UTC, nvkelso requested changes
See https://github.com/tangrams/cartography-docs/pull/35#issuecomment-328661041 to move Zinc to be a Refill theme.

2017-09-11 22:10 UTC, nvkelso commented
We did a poor job of talking about the built-in style `icons:` in the documentation so far... https://mapzen.com/documentation/cartography/icons/. We've resolved that in this PR, but...

But `labels:` was broadcast a few times like in Rhonda's https://mapzen.com/blog/lots-of-dots/#built-in-sprites.

For backwards compatibility we could add in the styles section:

```
    icons:
        base: mapzen_icon_library
```

But then remove it in the next major version?

2017-09-26 19:36 UTC, rmglennon commented
For migration_guide, could you give a more specific title so it's clear what people are migrating to and whether it affects them?

2017-09-26 19:48 UTC, nvkelso commented
@rmglennon re https://github.com/tangrams/cartography-docs/pull/35#issuecomment-332311350 do you have a recommendation, please?

Another option is to nest the migration guide into the semantic versioning section.

The migration guide is similar to the `Migrating to version 1.0` vector tiles documentation. For these cartography docs I don't want to do a migration guide for every single breaking change, but for significant changes this gives us a place to give some tips.

2017-09-26 19:57 UTC, rmglennon commented
Ah, if you intend to use this page again in the future, then you could add a heading above the Zinc with ## and then add a # to the current ones to make them nest under it. It sounds like it could be something like, "Migration to cartography version 6 (September 2017)"? 

I'm not sure how we refer to cartography releases myself, so that's why I added the comment. :)

2017-09-26 20:11 UTC, nvkelso commented
Yeah, it's complicated as each style is independently versioned – this is partly why I added the release management issue as even I was getting confused 😉 Sometimes they are released in a batch (like this PR described), sometimes it's just a single style being updated like Refill last month. And then the docs are also versioned for "public" release points but that's wishy-washy.

The current versions are (with this "release"):

- Bubble Wrap: `8.0.0`
- Cinnabar: `8.0.0`
- Refill: `9.0.0`
- Tron: `5.0.0`
- Walkabout: `6.0.0`

There are already two items in the [migration guide](https://github.com/tangrams/cartography-docs/blob/388207618245a5a2550f592e3a929dc96ad4a080/migration-guide.md): 

- **Zinc**
- **Named label variants**. 

Should I modify the headers so they say:

- **Named label variants (September 2017)** 
- **Zinc (September 2017)** 

And sort most recent at the top, and then a-z inside the same date range (so Zinc would move down)?

We don't have release notes per say right now in the documentation site. Instead those are only maintained in the source Github repo's release notes functionality.

2017-09-27 17:05 UTC, rmglennon commented
Whew, OK...sounds like a "use your judgement" situation on whether or not and how to identify them. :)

2017-10-02 15:52 UTC, nvkelso approved these changes
LGTM

2017-10-02 15:52 UTC, merged