add api key docs
tangrams/cartography-docs pull request #6
Opened 2016-11-17 17:01 UTC by kkowalsky

fixes #2 

@nvkelso I put the examples for Tangram JS and the YAML syntax together in the API Reference as it makes more sense. I could add it to 'Get Started' as well, but I don't think it's necessary. 

still unsure if the default = false?

2016-11-17 21:21 UTC, nvkelso commented
This is aspirational at the moment since no house style currently supports this API method.

Once they do, we can merge this.

We should probably add a bullet point to each house style in `styles.md` saying that it's not yet supported? (And when it is we'll move that bullet point to the supported column?)

2016-11-17 21:21 UTC, nvkelso requested changes

2016-11-17 21:21 UTC, nvkelso commented on api-reference.md
> +In the Tangram YAML file:
We don't include any other Tangram YAML file snippets for the other API methods. Recommend removing this title and code block.

2016-11-17 21:21 UTC, nvkelso commented on api-reference.md
> +## Global API keys
Global API keys or Mapzen API keys? Mapzen should either be in the section header or/& also in the paragraph text.

2016-11-17 21:22 UTC, nvkelso commented
Yes, the default will be false – which means the style would only have access to anonymous rate limits + cached tiles.

2016-11-28 20:36 UTC, nvkelso commented on api-reference.md
> +API keys can be set as a global variable which allows you to easily change them when starting a new project or updating your key. As API keys are not set to a particular product, you can use the same
This is a generic Tangram feature, not constrained to JS.

2016-11-30 19:18 UTC, kkowalsky commented
just noticed that https://mapzen.com/documentation/tangram/android-walkthrough/#using-mapzens-vector-tile-service uses this already in the walkthrough...

2017-01-06 04:49 UTC, nvkelso commented on api-reference.md
> +API keys can be set as a global variable which allows you to easily change them when starting a new project or updating your key. As API keys are not set to a particular product, you can use the same
API keys **should** be set using the global variable

2017-01-06 04:49 UTC, nvkelso commented on api-reference.md
> +* `sdk_api_key`: defaults to `false`
defaults to `''`

2017-01-06 04:50 UTC, nvkelso commented on api-reference.md
> +globals:
```
 var layer = Tangram.leafletLayer({
        scene: { import: style_file, global: { sdk_mapzen_api_key: 'mapzen-xxxxxx' } },
        attribution: '<a href="https://mapzen.com/tangram" target="_blank">Tangram</a> | &copy; OSM contributors | <a href="https://mapzen.com/" target="_blank">Mapzen</a>'
    });
```

2017-01-06 04:51 UTC, nvkelso commented on api-reference.md
> +API keys can be set as a global variable which allows you to easily change them when starting a new project or updating your key. As API keys are not set to a particular product, you can use the same
We should also link to getting an API key...

[Sign up](https://mapzen.com/documentation/overview/#developer-accounts-and-api-keys) for a Mapzen API key to enjoy higher rate limits...

2017-01-06 04:52 UTC, nvkelso commented on api-reference.md
> +globals:
And the Tangram ES version:

```
map->loadScene(
    "https://mapzen.com/carto/bubble-wrap-style/bubble-wrap.yaml",
    false,
    { "global.sdk_mapzen_api_key", "mapzen-xxxxxx" }
);
```

2017-01-06 04:52 UTC, nvkelso commented on api-reference.md
> +globals:
Waiting for Mapzen.js version (should be available next week).

2017-01-06 04:53 UTC, nvkelso commented on api-reference.md
> +globals:
(Remove the snippet of source code, that's internal logic the user shouldn't worry about.)

2017-01-21 00:09 UTC, nvkelso approved these changes

2017-01-21 00:09 UTC, merged